create table offer (
                       pk_offer bigint not null,
                       additional_info TEXT,
                       city TEXT not null,
                       company_benefits TEXT,
                       company_facilities TEXT,
                       company_offers TEXT,
                       contract TEXT not null,
                       introduction_date timestamp(6) not null,
                       salary_level TEXT not null,
                       offer_name TEXT not null,
                       photo_background bytea,
                       project_description TEXT,
                       requirenments TEXT,
                       salary_hour TEXT,
                       salary_status integer not null,
                       salary_undisc TEXT,
                       salary_year TEXT,
                       technology TEXT not null,
                       pk_account bigint,
                       primary key (pk_offer)
)
